"""Centralized configuration module for Weather Forecast & Alert Application.

Defines API endpoints, fair-use headers, CC BY 4.0 data attribution,
WMO code mappings, partitioned threshold configurations, and typed exceptions.
"""

from typing import Any, Dict, Tuple

# ---------------------------------------------------------------------------
# API Endpoints & Governance
# ---------------------------------------------------------------------------
GEOCODING_API_URL = "https://geocoding-api.open-meteo.com/v1/search"
FORECAST_API_URL = "https://api.open-meteo.com/v1/forecast"

API_REQUEST_TIMEOUT_SECONDS = 10.0
API_MAX_RETRY_ATTEMPTS = 3
API_RATE_LIMIT_SAFETY_CAP_SECONDS = 30.0

DEFAULT_USER_AGENT = "WeatherForecastAlertApp/1.0 (DeveloperPortfolio; Educational/Non-Commercial)"
DEFAULT_HEADERS = {
    "User-Agent": DEFAULT_USER_AGENT,
    "Accept": "application/json",
}

# Mandatory Legal & Attribution Notices (CC BY 4.0 and Scientific Ethics)
ATTRIBUTION_NOTICE = "Weather data provided by Open-Meteo.com under CC BY 4.0."
NON_OFFICIAL_DISCLAIMER = (
    "[APPLICATION NOTICE] Generated by rule threshold evaluation. "
    "This is not an official meteorological warning."
)
ALERT_ORIGIN_TAG = "APPLICATION_RULE_ENGINE"
ALERT_DISCLAIMER_TEXT = (
    "Synthetic rule advisory evaluated against local thresholds; "
    "not an official government warning."
)

DEFAULT_CITY = "Pune"

# ---------------------------------------------------------------------------
# Typed Domain Exceptions
# ---------------------------------------------------------------------------
class WeatherAppException(Exception):
    """Base application exception."""


class CityNotFoundError(WeatherAppException):
    """Raised when geocoding returns HTTP 200 with an empty results list: results == []."""


class APIConnectionError(WeatherAppException):
    """Raised when network connection drops, DNS fails, or socket times out after retries are exhausted."""


class APIRateLimitError(WeatherAppException):
    """Raised when HTTP 429 Too Many Requests persists after retries / Retry-After backoff are exhausted."""


class APIResponseError(WeatherAppException):
    """Raised on permanent response defects: missing 'results' key, malformed JSON, or non-retryable 4xx client errors."""


class APIServerError(APIResponseError):
    """Raised when upstream HTTP 5xx server errors persist after all retry attempts are exhausted."""


# ---------------------------------------------------------------------------
# WMO Interpretation Dictionary & Safe Fallback
# ---------------------------------------------------------------------------
WMO_CODE_TABLE: Dict[int, Tuple[str, str]] = {
    0: ("Clear", "Clear sky"),
    1: ("Clouds", "Mainly clear, partly cloudy, or overcast"),
    2: ("Clouds", "Mainly clear, partly cloudy, or overcast"),
    3: ("Clouds", "Mainly clear, partly cloudy, or overcast"),
    45: ("Fog", "Fog and depositing rime fog"),
    48: ("Fog", "Fog and depositing rime fog"),
    51: ("Drizzle", "Drizzle: Light, moderate, or dense intensity"),
    53: ("Drizzle", "Drizzle: Light, moderate, or dense intensity"),
    55: ("Drizzle", "Drizzle: Light, moderate, or dense intensity"),
    56: ("Freezing Drizzle", "Freezing drizzle: Light or dense intensity"),
    57: ("Freezing Drizzle", "Freezing drizzle: Light or dense intensity"),
    61: ("Rain", "Rain: Slight or moderate intensity"),
    63: ("Rain", "Rain: Slight or moderate intensity"),
    65: ("Rain", "Rain: Heavy intensity"),
    66: ("Freezing Rain", "Freezing rain: Light or heavy intensity"),
    67: ("Freezing Rain", "Freezing rain: Light or heavy intensity"),
    71: ("Snow", "Snow fall: Slight, moderate, or heavy"),
    73: ("Snow", "Snow fall: Slight, moderate, or heavy"),
    75: ("Snow", "Snow fall: Slight, moderate, or heavy"),
    77: ("Snow", "Snow grains"),
    80: ("Showers", "Rain showers: Slight or moderate"),
    81: ("Showers", "Rain showers: Violent intensity"),
    82: ("Showers", "Rain showers: Violent intensity"),
    85: ("Snow", "Snow showers: Slight or heavy"),
    86: ("Snow", "Snow showers: Slight or heavy"),
    95: ("Thunderstorm", "Thunderstorm: Slight or moderate"),
    96: ("Thunderstorm", "Thunderstorm with slight or heavy hail"),
    99: ("Thunderstorm", "Thunderstorm with slight or heavy hail"),
}


def get_wmo_interpretation(code: int) -> Tuple[str, str]:
    """Return (weather_category, weather_description) with safe fallback for unknown codes."""
    if code in WMO_CODE_TABLE:
        return WMO_CODE_TABLE[code]
    return ("Unknown", f"Unknown weather code ({code})")


# ---------------------------------------------------------------------------
# Default Partitioned Alert Configuration (CURRENT, HOURLY, DAILY)
# ---------------------------------------------------------------------------
DEFAULT_ALERT_CONFIG: Dict[str, Dict[str, Any]] = {
    "CURRENT": {
        "EXTREME_HEAT_CRITICAL": 38.0,
        "EXTREME_HEAT_WARNING": 35.0,
        "EXTREME_COLD_CRITICAL": -5.0,
        "EXTREME_COLD_WARNING": 0.0,
        "WIND_SPEED_CRITICAL": 75.0,
        "WIND_SPEED_WARNING": 50.0,
        "SEVERE_WMO_CRITICAL": [66, 67, 82, 96, 99],
        "SEVERE_WMO_WARNING": [65, 75, 86, 95],
        "HEAT_DISCOMFORT_ADVISORY_TEMP": 30.0,
        "HEAT_DISCOMFORT_ADVISORY_HUMIDITY": 80,
    },
    "HOURLY": {
        "EXTREME_HEAT_CRITICAL": 38.0,
        "EXTREME_HEAT_WARNING": 35.0,
        "EXTREME_COLD_CRITICAL": -5.0,
        "EXTREME_COLD_WARNING": 0.0,
        "PRECIP_1H_CRITICAL": 25.0,
        "PRECIP_1H_WARNING": 10.0,
        "WIND_SPEED_CRITICAL": 75.0,
        "WIND_SPEED_WARNING": 50.0,
        "SEVERE_WMO_CRITICAL": [66, 67, 82, 96, 99],
        "SEVERE_WMO_WARNING": [65, 75, 86, 95],
        "HEAT_DISCOMFORT_ADVISORY_TEMP": 30.0,
        "HEAT_DISCOMFORT_ADVISORY_HUMIDITY": 80,
    },
    "DAILY": {
        "DAILY_PEAK_HEAT_CRITICAL": 38.0,
        "DAILY_PEAK_HEAT_WARNING": 35.0,
        "DAILY_FREEZE_CRITICAL": -5.0,
        "DAILY_FREEZE_WARNING": 0.0,
        "PRECIP_24H_CRITICAL": 100.0,
        "PRECIP_24H_WARNING": 50.0,
        "DAILY_MAX_WIND_CRITICAL": 75.0,
        "DAILY_MAX_WIND_WARNING": 50.0,
        "SEVERE_WMO_CRITICAL": [66, 67, 82, 96, 99],
        "SEVERE_WMO_WARNING": [65, 75, 86, 95],
    },
}

# Severity Precedence Hierarchy
SEVERITY_PRECEDENCE = {
    "CRITICAL": 3,
    "WARNING": 2,
    "ADVISORY": 1,
    "NONE": 0,
}

# ---------------------------------------------------------------------------
# Simulator Defaults
# ---------------------------------------------------------------------------
SIMULATOR_DEFAULT_SEED = 42
SIMULATOR_DEFAULT_REF_TIME = "2026-09-27T00:00:00Z"
